name: Basic Checkout Lab
on:
  push: 
    branches:
      - main

jobs:
  basic-checkout:
    runs-on: ubuntu-latest
    env:
      CUSTOM_MESSAGE: "Hello from GitHub Actions!"
    steps:
      #checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
      #list repository contents
      - name: List files
        run: ls -la
        
      #display system information
      - name: Show system info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Operating System: $(uname -a)"
          echo "Current Directory: $(pwd)"

      #check software versions
      - name: Check versions
        run: |
          echo "Node version: $(node --version)"
          echo "Python version: $(python --version)"
          echo "Git version: $(git --version)"

      #more information
      - name: Show more info
        run: |
          echo "Current Date:$(date)"
          echo "Available Disk Space:$(df -h)"
          echo "Memory Usage:$(free -m)"

      #print environment variable
      - name: Print env
        run: echo "$CUSTOM_MESSAGE"

      #executing on condition
      - name: Conditional step
        if: github.event_name == 'push'
        run: echo "This was triggered by a push event"
        
          
