name: Build-test-deploy
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: build-step
        run: echo "The step is building"

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name : test-step
        run: |
          echo "Test is running"
          echo "Test completed"
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: deploy-step
        run: |
          echo "Deployment started"
      
        
        
