#this is a basic workflow that prints hello world messages
name: Hello World
on: workflow_dispatch
jobs:
  hello-world-multi-step:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
          echo "Hello Multi step command"
          name="Asif"
          echo "My name is $name"
  
