#this is a simple workflow to print hello asif message
name: Hello-asif
on: workflow_dispatch
jobs:
  hello-asif:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
          echo "Hello Asif"
          echo "Hello World"
          name="Asif"
          age=25
          echo My name is $name and age is $age
