name: Multiple Jobs in Single File
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: |
          build=1.0
          echo "Build version $build"
          echo "A demo build"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name : Test step
        run: |
          echo "Test cases passed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "Build completed"
