name: Variable and Secrets
on: push
jobs:
  Variable:
    runs-on: ubuntu-latest
    steps:
      - name: Variable Info
        run: echo "My name is ${{vars.USER_NAME}}"
  Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Info
        run: echo "Docker Password is ${{secrets.DOCKER_PASSWORD}}"
        
